export const deliveryCountries = [
  { country: "Select Country" },
  { country: "Australia" },
  { country: "Austria" },
  { country: "Belgium" },
  { country: "Bulgaria" },
  { country: "Coratia" },
  { country: "Chech Republic" },
  { country: "Denmark" },
  { country: "Estonia" },
  { country: "Finland" },
  { country: "France" },
  { country: "Greece" },
  { country: "Spain" },
  { country: "India" },
  { country: "Ireland" },
  { country: "Izrael", price: 50 },
  { country: "Lithuania" },
  { country: "Luxembourg" },
  { country: "Latvia" },
  { country: "Netherlands" },
  { country: "Germany" },
  { country: "Portugal" },
  { country: "Romania" },
  { country: "Slovakia" },
  { country: "Slovenia" },
  { country: "Switzerland" },
  { country: "Sweden" },
  { country: "Turkey" },
  { country: "Hungary" },
  { country: "Greate Britain" },
  { country: "Italy" },
  { country: "United States" },
  { country: "Cyprus" },
].sort((a, b) => a.country.localeCompare(b.country));
