export const deliveryPriceArr = [
  { country: "Select Country", price: 0 },
  { country: "Australia", price: 150 },
  { country: "Austria", price: 20 },
  { country: "Belgium", price: 20 },
  { country: "Bulgaria", price: 35 },
  { country: "Coratia", price: 35 },
  { country: "Chech Republic", price: 20 },
  { country: "Denmark", price: 20 },
  { country: "Estonia", price: 20 },
  { country: "Finland", price: 35 },
  { country: "France", price: 30 },
  { country: "Greece", price: 35 },
  { country: "Spain", price: 30 },
  { country: "India", price: 150 },
  { country: "Ireland", price: 35 },
  { country: "Izrael", price: 150 },
  { country: "Lithuania", price: 20 },
  { country: "Luxembourg", price: 25 },
  { country: "Latvia", price: 20 },
  { country: "Netherlands", price: 20 },
  { country: "Germany", price: 20 },
  { country: "Portugal", price: 30 },
  { country: "Romania", price: 30 },
  { country: "Slovakia", price: 20 },
  { country: "Slovenia", price: 30 },
  { country: "Switzerland", price: 150 },
  { country: "Sweden", price: 35 },
  { country: "Turkey", price: 150 },
  { country: "Hungary", price: 20 },
  { country: "Greate Britain", price: 30 },
  { country: "Italy", price: 30 },
  { country: "United States", price: 50 },
  { country: "Cyprus", price: 30 },
].sort((a, b) => a.country.localeCompare(b.country));
