export const storageItem = {
  id: 1,
  attributes: {
    name: 'Kierownica Audi',
    slug: 'kierownica-audi',
    description: 'super jest ta kierownica',
    available: null,
    createdAt: '2022-06-18T21:49:43.504Z',
    updatedAt: '2022-06-21T21:00:46.532Z',
    publishedAt: '2022-06-18T21:51:04.610Z',
    price: 100,
    image: {
      data: [
        {
          id: 2,
          attributes: {
            name: 'Toyota.jpg',
            alternativeText: 'Toyota.jpg',
            caption: 'Toyota.jpg',
            width: 1440,
            height: 1440,
            formats: {
              thumbnail: {
                name: 'thumbnail_Toyota.jpg',
                hash: 'thumbnail_Toyota_c8e4c8b08c',
                ext: '.jpg',
                mime: 'image/jpeg',
                path: null,
                width: 156,
                height: 156,
                size: 4.92,
                url: '/uploads/thumbnail_Toyota_c8e4c8b08c.jpg',
              },
              large: {
                name: 'large_Toyota.jpg',
                hash: 'large_Toyota_c8e4c8b08c',
                ext: '.jpg',
                mime: 'image/jpeg',
                path: null,
                width: 1000,
                height: 1000,
                size: 80.38,
                url: '/uploads/large_Toyota_c8e4c8b08c.jpg',
              },
              medium: {
                name: 'medium_Toyota.jpg',
                hash: 'medium_Toyota_c8e4c8b08c',
                ext: '.jpg',
                mime: 'image/jpeg',
                path: null,
                width: 750,
                height: 750,
                size: 51.76,
                url: '/uploads/medium_Toyota_c8e4c8b08c.jpg',
              },
              small: {
                name: 'small_Toyota.jpg',
                hash: 'small_Toyota_c8e4c8b08c',
                ext: '.jpg',
                mime: 'image/jpeg',
                path: null,
                width: 500,
                height: 500,
                size: 28.4,
                url: '/uploads/small_Toyota_c8e4c8b08c.jpg',
              },
            },
            hash: 'Toyota_c8e4c8b08c',
            ext: '.jpg',
            mime: 'image/jpeg',
            size: 112.62,
            url: '/uploads/Toyota_c8e4c8b08c.jpg',
            previewUrl: null,
            provider: 'local',
            provider_metadata: null,
            createdAt: '2022-06-18T21:49:35.680Z',
            updatedAt: '2022-06-18T21:49:35.680Z',
          },
        },
      ],
    },
    config: {
      id: 1,
      boki: true,
      gora_i_dol: true,
      kolor_nici: true,
      pasek_gora: true,
      blenda: true,
      multifunkcja: true,
      airbag: true,
    },
  },
  quantity: 1,
  price: 234,
};
